my_blog/director/urls.py
from django.urls import path

from director import views

app_name = "director"
urlpatterns = [
    path("directors", views.directors, name="director-list"),
    path("director/add", view=views.create_directors, name="director-add"),
]

my_blog/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="home"),
    path("search/", views.search, name="search"),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('actor/', include("actor.urls")),
    path('director/', include("director.urls")),
    path('movie/', include("movie.urls")),
    
]

my_blog/director/models.py
from django.db import models

class Director(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    birth = models.DateField()
    movies = models.IntegerField()

    def __str__(self):
        return f"Name: {self.name} - Last_name: {self.last_name} - Birth: {self.birth} - Movies: {self.movies}"

my_blog/director/forms.py
from django import forms


from director.models import Director

class DirectorForm(forms.Form):
    name = forms.CharField(
        label="Nombre del director/a",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "director-name",
                "placeholder": "introduzca nombre",
                "required": "True",
            }
        ),
    )   
    last_name = forms.CharField(
        label="apellido del director/a",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "director-last_name",
                "placeholder": "introduzca apellido",
                "required": "True",
            }      
        ),
    )
    birth = forms.DateField(
        label="fecha de nacimiento",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "director-birth",
                "placeholder": "introduzca fecha de nacimiento",
                "required": "True",
            }
        ),
    )
    movies = forms.IntegerField(
        label="cantidad de peliculas",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "director-movies",
                "placeholder": "introduzca cantidad de peliculas",
                "required": "True",
            }
        ),
    )
    class Meta:
        model = Director
        fields = ["name", "last_name", "birth", "movies",]

my_blog/director/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib import messages


from director.models import Director
from director.forms import DirectorForm

def directors(request):
    return render(
        request=request,
        context={"director_list": get_directors(request)},
        template_name="director/director_list.html",
        ) 
        
def get_directors(request):
    directors = Director.objects.all()
    paginator = Paginator(directors, 3)
    page_number = request.GET.get("page")
    return paginator.get_page(page_number)

def create_directors (request):
    if request.method == "POST":
            director_form = DirectorForm(request.POST)
            if director_form.is_valid():
                data = director_form.cleaned_data
                actual_objects = Director.objects.filter(
                    name=data["name"], last_name=data["last_name"], birth=data["birth"], movies=data["movies"]
                ).count()
                print("actual_objects", actual_objects)
                if not actual_objects:
                    director = Director(
                        name=data["name"],
                        last_name=data["last_name"],
                        birth=data["birth"],
                        movies=data["movies"],
                        
                    )
                    director.save()
                    messages.success(
                        request,
                        f"Director {data['name']} - {data['last_name']} - {data['birth']} - {data['movies']} creado exitosamente!",
                    )
                    return render(
                        request=request,
                        context={"director_list": get_directors(request)},
                        template_name="director/director_list.html",
                    )
                else:
                    messages.error(
                        request,
                        f"El director {data['name']} - {data['last_name']} - {data['birth']} - {data['movies']} ya está creado",
                    )



    director_form = DirectorForm(request.POST)
    context_dict = {"form": director_form}
    return render(
        request=request,
        context=context_dict,
        template_name="director/director_form.html",
    )
        

my_blog/director/templates/director/director_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar directores</h2>
                    <span class="subheading">My blog</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar director" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/director/templates/director/director_list.html
{% extends "home/index.html" %}
{% load static %}
{% block my_blog_header %}
<header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Lista de Directores</h1>
                    <span class="subheading">My blog</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'director:director-add' %}">Crear nuevo director</a>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            
            {% for director in director_list %}
                <!-- Post preview-->
                <div class="post-preview">
                        <h2 class="post-title">{{ director.name }} {{ director.last_name }}</h2>
                        <h3 class="post-subtitle">Produjo  {{ director.movies }} peliculas </h3>
                        <h4 class="post-subtitle">Fecha de nacimiento: {{ director.birth }}</h4>
                        

                        

                </div>        
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

<!--Pagination-->
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if director_list.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ director_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if director_list.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ director_list.number }} of {{ director_list.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if director_list.has_next %}
                <a href="?page={{ director_list.next_page_number }}">next</a> |
                <a href="?page={{ director_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<!--end of Pagination-->

<!--Pagination Class Based Views-->
{% if is_paginated %}
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ director_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if page_obj.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a> |
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<!--end of Pagination-->

{% endblock %}