my_blog/actor/urls.py
from django.urls import path

from actor import views

app_name = "actor"
urlpatterns = [
    path("actors", views.actors, name="actor-list"),
    path("actor/add", view=views.create_actors, name="actor-add"),
]

my_blog/director/urls.py
from django.urls import path

from director import views

app_name = "director"
urlpatterns = [
    path("directors", views.directors, name="director-list"),
    path("director/add", view=views.create_directors, name="director-add"),
]

my_blog/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="home"),
    path("search/", views.search, name="search"),
]

my_blog/movie/urls.py
from django.urls import path

from movie import views

app_name = "movie"
urlpatterns = [
    path("movies/", views.MovieListView.as_view(), name="movie-list"),
    path("movie/add/", views.MovieCreateView.as_view(), name="movie-add"),
    path("movie/<int:pk>/detail/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("movie/<int:pk>/update/", views.MovieUpdateView.as_view(), name="movie-update"),
    path("movie/<int:pk>/delete/", views.MovieDeleteView.as_view(), name="movie-delete"),

]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('actor/', include("actor.urls")),
    path('director/', include("director.urls")),
    path('movie/', include("movie.urls")),
    
]

my_blog/home/models.py
from django.db import models

# Create your models here.

my_blog/home/views.py
from django.shortcuts import render
from django.db.models import Q

from actor.models import Actor
from director.models import Director
from movie.models import Movie

def index(request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )

def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    if search_param:
        query = Q(name__contains=search_param)
        query.add(Q(release_date__contains=search_param), Q.OR)
        movies = Movie.objects.filter(query)
        context_dict.update(
            {
               "search_param": search_param,
                "movies": movies
               
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/index.html",
    )

my_blog/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block my_blog_title %}
                Moviedata-
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'movie:movie-list' %}">Movies</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'director:director-list' %}">Directors</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'actor:actor-list' %}">Actors</a></li>
                        
                    </ul>
                </div>
            </div>
        </nav>
        {% block my_blog_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Movie Data</h1>
                            <span class="subheading">By LucasLezcano</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Messages-->
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">       
                    <!-- Post preview-->
                    {% block my_blog_content %}
                    <!-- Buscador -->
                    <h2>Buscador de peliculas</h2>
                    <form action="{% url 'home:search' %}" method="GET">
                        <div>
                            <input type="text" name="search_param" id="movie_name_or_last_name" placeholder="Buscar.."
                            {% if search_param %} value="{{ search_param }}" {% endif %}
                            >
                            <input type="submit" value="Buscar">
                            <a style="color: black" href="{% url 'home:home' %}"><i class="fa fa-undo"></i></a>
                        </div>
                    </form>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Si hay resultados en el buscador los presenta -->
                    {% if movies %}
                    {% for movie in movies %}
                        <!-- Post preview-->
                        <div class="post-preview">
                                <h2 class="post-title">{{ movie.name }}</h2>
                                <h3 class="post-subtitle">Fecha de estreno {{ movie.release_date }}</h3>
                                <h4 class="post-subtitle">Producida por :  {{ movie.produced_by}}</h4>                                    
                        </div>        
                        <!-- Divider-->
                        <hr class="my-4" />  
                    {% endfor %}
                    {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>