my_blog/actor/urls.py
from django.urls import path

from actor import views

app_name = "actor"
urlpatterns = [
    path("actors", views.actors, name="actor-list"),
    path("actor/add", view=views.create_actors, name="actor-add"),
]

my_blog/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="home"),
    path("search/", views.search, name="search"),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('actor/', include("actor.urls")),
    path('director/', include("director.urls")),
    path('movie/', include("movie.urls")),
    
]

my_blog/actor/models.py
from django.db import models

class Actor(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    awards = models.IntegerField()

    def __str__(self):
        return f"Name:{self.name} - Last_name: {self.last_name} - Awards: {self.awards}"

my_blog/actor/forms.py
#from ckeditor.widgets import CKEditorWidget
from django import forms


from actor.models import Actor

class ActorForm(forms.Form):
    name = forms.CharField(
        label="Nombre del actor/actriz",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "actor-name",
                "placeholder": "introduzca nombre",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del actor/actriz",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "actor-last_name",
                "placeholder": "introduzca apellido",
                "required": "True",
            }
        ),
    )
    awards = forms.IntegerField(
        label="Premios del actor/a",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "actor-awards",
                "placeholder": "introduzca cantidad de premios",
                "required": "True",
            }
        ),
    )

    class Meta:
        model = Actor
        fields = ["name", "last_name", "awards"]

my_blog/actor/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib import messages


from actor.models import Actor
from actor.forms import ActorForm  

def actors(request):
    return render(
        request=request,
        context={"actor_list": get_actors(request)},
        template_name="actor/actor_list.html",
    )
def get_actors(request):
    actors = Actor.objects.all()
    paginator = Paginator(actors, 3)
    page_number = request.GET.get("page")
    return paginator.get_page(page_number)



def create_actors(request):
    if request.method == "POST":
        actor_form = ActorForm(request.POST)
        if actor_form.is_valid():
            data = actor_form.cleaned_data
            actual_objects = Actor.objects.filter(
                name=data["name"], last_name=data["last_name"], awards=data["awards"]
            ).count()
            print("actual_objects", actual_objects)
            if not actual_objects:
                actor = Actor(
                    name=data["name"],
                    last_name=data["last_name"],
                    awards=data["awards"],
                )
                actor.save()
                messages.success(
                    request,
                    f"Actor {data['name']} - {data['last_name']} - {data['awards']} creado exitosamente!",
                )
                return render(
                    request=request,
                    context={"actor_list": get_actors(request)},
                    template_name="actor/actor_list.html",
                )
            else:
                messages.error(
                    request,
                    f"El actor {data['name']} - {data['last_name']} - {data['awards']} ya está creado",
                )



    actor_form = ActorForm(request.POST)
    context_dict = {"form": actor_form}
    return render(
        request=request,
        context=context_dict,
        template_name="actor/actor_form.html",
    )




            

    

my_blog/actor/templates/actor/actor_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar actores</h2>
                    <span class="subheading">My blog</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar actor" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/actor/templates/actor/actor_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Lista de Actores</h1>
                    <span class="subheading">My blog</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'actor:actor-add' %}">Crear nuevo actor</a>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
{% for actor in actor_list %}
                <!-- Post preview-->
                <div class="post-preview">
                        <h2 class="post-title">{{ actor.name }} {{ actor.last_name }}</h2>
                        <h3 class="post-subtitle">Tiene  {{ actor.awards }} premios </h3>
                        

                </div>        
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

<!--Pagination-->
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if actor_list.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ actor_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if actor_list.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ actor_list.number }} of {{ actor_list.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if actor_list.has_next %}
                <a href="?page={{ actor_list.next_page_number }}">next</a> |
                <a href="?page={{ actor_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<!--end of Pagination-->

<!--Pagination Class Based Views-->
{% if is_paginated %}
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ actor_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if page_obj.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a> |
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<!--end of Pagination-->

{% endblock %}