my_blog/home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="home"),
    path("search/", views.search, name="search"),
]

my_blog/movie/urls.py
from django.urls import path

from movie import views

app_name = "movie"
urlpatterns = [
    path("movies/", views.MovieListView.as_view(), name="movie-list"),
    path("movie/add/", views.MovieCreateView.as_view(), name="movie-add"),
    path("movie/<int:pk>/detail/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("movie/<int:pk>/update/", views.MovieUpdateView.as_view(), name="movie-update"),
    path("movie/<int:pk>/delete/", views.MovieDeleteView.as_view(), name="movie-delete"),

]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('actor/', include("actor.urls")),
    path('director/', include("director.urls")),
    path('movie/', include("movie.urls")),
    
]

my_blog/movie/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator


class Movie(models.Model):
    name = models.CharField(max_length=40)
    release_date = models.DateField()
    produced_by = models.CharField(max_length=40)
    description = RichTextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "name",
            "produced_by",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Movie: {self.name} | produced_by: {self.produced_by}"

        
class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

my_blog/movie/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from movie.models import Movie

class MovieForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre de la pelicula",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "movie-name",
                "placeholder": "introduzca nombre de la pelicula",
                "required": "True",
            }
        ),
    )
    
    release_date = forms.DateField(
        label="NFecha de estreno",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "movie-name",
                "placeholder": "introduzca fecha de estreno",
                "required": "True",
            }
        ),
    )
    produced_by = forms.CharField(
        label="Dirigida por : ",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "movie-produced_by",
                "placeholder": "introduzca nombre del director/a",
                "required": "True",
            }
        ),
    )

    description = forms.CharField(
        label="Descripción:",
        required=False,
        widget=CKEditorWidget(
            attrs={
                "class": "movie-description",
                "placeholder": "Descripcion de la pelicula",
                "required": "True",
            }
        ),
    )
    class Meta:
        model = Movie
        fields = ["name", "release_date", "produced_by", "description"] 

my_blog/movie/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from movie.models import Comment

from movie.models import Movie
from movie.forms import MovieForm


class MovieListView(ListView):
    model = Movie
    paginate_by = 3


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movie/movie_detail.html"
    fields = ["name", "release_date", "produced_by", "description"]

    def get(self, request, pk):
        movie = Movie.objects.get(id=pk)
#        comments = Comment.objects.filter(movie=movie).order_by("-updated_at")
#        comment_form = CommentForm()
        context = {
            "movie": movie,
#            "comments": comments,
#           "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class MovieCreateView(LoginRequiredMixin, CreateView):
    model = Movie
    success_url = reverse_lazy("movie:movie-list")

    form_class = MovieForm
    #fields = ["name", "release_date", "produced_by", "description"]

    def form_valid(self, form):
        """Filter to avoid duplicate movies"""
        data = form.cleaned_data
        #form.instance.owner = self.request.user
        actual_objects = Movie.objects.filter(
            name=data["name"], produced_by=data["produced_by"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La pelicula {data['name']} - {data['produced_by']} ya está creada",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Pelicula {data['name']} - {data['produced_by']} creada exitosamente!",
            )
            return super().form_valid(form)


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    model = Movie
    fields = ["name", "release_date", "produced_by", "description"]

    def get_success_url(self):
        movie_id = self.kwargs["pk"]
        return reverse_lazy("movie:movie-detail", kwargs={"pk": movie_id})


class MovieDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy("movie:movie-list")


#class CommentCreateView(LoginRequiredMixin, CreateView):
#    def post(self, request, pk):
#        movie = get_object_or_404(Movie, id=pk)
#        comment = Comment(
#            text=request.POST["comment_text"], owner=request.user, movie=movie
#        )
#        comment.save()
#        return redirect(reverse("movie:movie-detail", kwargs={"pk": pk}))
#
#
#class CommentDeleteView(LoginRequiredMixin, DeleteView):
#    model = Comment
#
#    def get_success_url(self):
#        movie = self.object.movie
#        return reverse("movie:movie-detail", kwargs={"pk": movie.id})
#




#
#def movies(request):
#    movies = Movie.objects.all() 
#
#    context_dict = {"movies": movies}
#
#    return render(
#        request=request,
#        context={"movie_list": get_movies(request)},
#        template_name="movie/movie_list.html",
#    )
#def get_movies(request):
#    movies = Movie.objects.all()
#    paginator = Paginator(movies, 3)
#    page_number = request.GET.get("page")
#    return paginator.get_page(page_number)
#
#
#def create_movies (request):
#    if request.method == "POST":
#            movie_form = MovieForm(request.POST)
#            if movie_form.is_valid():
#                data = movie_form.cleaned_data
#                actual_objects = Movie.objects.filter(
#                    name=data["name"], release_date=data["release_date"], produced_by=data["produced_by"]
#                ).count()
#                print("actual_objects", actual_objects)
#                if not actual_objects:
#                    movie = Movie(
#                        name=data["name"],
#                        release_date=data["release_date"],
#                        produced_by=data["produced_by"],
#                    )
#                    movie.save()
#                    messages.success(
#                        request,
#                        f"Movie {data['name']} - {data['release_date']} - {data['produced_by']} creado exitosamente!",
#                    )
#                    return render(
#                        request=request,
#                        context={"movie_list": get_movies(request)},
#                        template_name="movie/movie_list.html",
#                    )
#                else:
#                    messages.error(
#                        request,
#                        f"El movie {data['name']} - {data['release_date']} - {data['produced_by']} ya está creado",
#                    )
#
#
#
#    movie_form = MovieForm(request.POST)
#    context_dict = {"form": movie_form}
#    return render(
#        request=request,
#        context=context_dict,
#        template_name="movie/movie_form.html",
#    )
#
#
#def movie_detail(request, pk: int):
#    return render(
#        request=request,
#        context={"movie": Movie.objects.get(pk=pk)},
#        template_name="movie/movie_detail.html",
#    )
#
#
#def movie_update(request, pk: int):
#    movie = Movie.objects.get(pk=pk)
#
#    if request.method == "POST":
#        movie_form = MovieForm(request.POST)
#        if movie_form.is_valid():
#            data = movie_form.cleaned_data
#            movie.name = data["name"]
#            movie.release_date = data["release_date"]
#            movie.produced_by = data["produced_by"]
#            movie.description = data["description"]           
#            movie.save()
#
#            return render(
#                request=request,
#                context={"movie": movie},
#                template_name="movie/movie_detail.html",
#            )
#
#    movie_form = MovieForm(model_to_dict(movie))
#    context_dict = {
#        "movie": movie,
#        "form": movie_form,
#    }
#    return render(
#        request=request, context=context_dict, template_name="movie/movie_form.html"
#    )
#
#def movie_delete(request, pk: int):
#    movie = Movie.objects.get(pk=pk)
#    if request.method == "POST":
#        movie.delete()
#
#        movies = Movie.objects.all()
#        context_dict = {"movie_list": movies}
#        return render(
#            request=request,
#            context=context_dict,
#            template_name="movie/movie_list.html",
#        )
#
#    context_dict = {
#        "movie": movie,
#    }
#    return render(
#        request=request,
#        context=context_dict,
#        template_name="movie/movie_delete.html",
#    )
#
#
#
#from django.core.exceptions import ValidationError
#from django.urls import reverse_lazy
#from django.views.generic import ListView
#from django.views.generic.detail import DetailView
#from django.views.generic.edit import CreateView, UpdateView, DeleteView
#
#from movie.models import Movie
#
#class MovieListView(ListView):
#    model: Movie
#    paginate_by = 3
#
#
#class MovieDetailView(DetailView):
#    model = Movie
#    template_name = "movie/movie_detail.html"
#    fields = ["name", "release_date", "produced_by", "description",]
#
#class MovieCreateView(CreateView):
#    model = Movie
#    success_url = reverse_lazy("movie:movie-list")
#
#    form_class = MovieForm
#    # fields = ["name", "release_date", "produced_by", "description"]
#
#    def form_valid(self, form):
#        """Filter to avoid duplicate movies"""
#        data = form.cleaned_data
#        actual_objects = Movie.objects.filter(
#            name=data["name"], reselase_date=data["reselase_date"], produced_by=data["produced_by"],
#        ).count()
#        if actual_objects:
#            messages.error(
#                self.request,
#                f"La pelicula {data['name']} - {data['reselase_date']} - {data['produced_by']} ya está creado",
#            )
#            form.add_error("name", ValidationError("Acción no válida"))
#            return super().form_invalid(form)
#        else:
#            messages.success(
#                self.request,
#                f"movie {data['name']} - {data['reselase_date']} - {data['produced_by']} creado exitosamente!",
#            )
#            return super().form_valid(form)
#
#
#class MovieUpdateView(UpdateView):
#    model = Movie
#    fields = ["name", "reselase_date", "produced_by", "description"]
#
#    def get_success_url(self):
#        movie_id = self.kwargs["pk"]
#        return reverse_lazy("movie:movie-detail", kwargs={"pk": movie_id})
#
#
#class MovieDeleteView(DeleteView):
#    model = Movie
#    success_url = reverse_lazy("movie:movie-list")
#

my_blog/movie/templates/movie/movie_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Movie delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1> Data-Movie </h1>
                    <span class="subheading">Eliminar pelicula</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'movie:movie-add' %}">Crear nueva pelicula</a>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}

<h1>Estás seguro de eliminar la pelicula: {{ movie.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'movie:movie-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/movie/templates/movie/movie_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Movie detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1> Data-Movie </h1>
                    <span class="subheading">Detalles de Peliculas</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'movie:movie-add' %}">Crear nueva pelicula</a>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle"> {{ movie.name }}</h3>
    <p class="post-meta">
        Creado por
        <a href="#!"> {{ movie.produced_by }} </a>
    <br>
        Fecha de estreno
        <a href="#!"> {{ movie.release_date }} </a>

    </p>
    <p class="card-text ">{{ movie.description|safe }}</p>
    <p style="text-align: center">
        <a href="{% url 'movie:movie-update' movie.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'movie:movie-delete' movie.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
        </a>    
    </p>
</div>
 
    
{% endblock %}
 

my_blog/movie/templates/movie/movie_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar peliculas</h2>
                    <span class="subheading">My blog</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar pelicula" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/movie/templates/movie/movie_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Movie-Data</h1>
                    <span class="subheading">Lista de Peliculas</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'movie:movie-add' %}">Crear nueva pelicula</a>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            
            {% for movie in movie_list %}
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'movie:movie-detail' movie.id %}">
                        <h2 class="post-title">{{ movie.name }}</h2>
                </div>        
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}
<!--Pagination-->
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if movie_list.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ movie_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if movie_list.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ movie_list.number }} of {{ movie_list.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if movie_list.has_next %}
                <a href="?page={{ movie_list.next_page_number }}">next</a> |
                <a href="?page={{ movie_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<!--end of Pagination-->

<!--Pagination Class Based Views-->
{% if is_paginated %}
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ movie_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if page_obj.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a> |
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<!--end of Pagination-->

{% endblock %}